apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        # IMPORTANT: Replace with your Docker Hub username
        # The 'latest' tag will be replaced by our CI/CD pipeline
        image: nishanthhks/client:latest
        ports:
        - containerPort: 80