apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: nishanthhks/server:1fd99f928f985e9db4dae8ade78633164651715c
        ports:
        - containerPort: 3000
        env:
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: server-secrets   # locate the Secret
                key: JWT_SECRET
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: server-secrets
                key: DATABASE_URL
